# Generated by Django 4.2.7 on 2023-11-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_buy_farmer_sell_animal_delete_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='selling',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
