# Generated by Django 4.2.7 on 2023-11-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_farmer_selling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='selling',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
