# Generated by Django 4.2.7 on 2023-11-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_alter_farmer_selling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_animal',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
