# Generated by Django 4.2.7 on 2023-11-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_alter_sell_animal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_animal',
            name='photo',
            field=models.CharField(max_length=20),
        ),
    ]
